USE [TP_DWH_MCD_2025]
GO

Select * from [LOG].[AUDIT_STATUS_PROCESS];

INSERT INTO  [LOG].[AUDIT_STATUS_PROCESS]
values
('RUNNING',GETDATE(),SYSTEM_USER,1);
INSERT INTO  [LOG].[AUDIT_STATUS_PROCESS]
values
('ABORT',GETDATE(),SYSTEM_USER,1);
INSERT INTO  [LOG].[AUDIT_STATUS_PROCESS]
values
('FINISH',GETDATE(),SYSTEM_USER,1);
INSERT INTO  [LOG].[AUDIT_STATUS_PROCESS]
values
('FINISH WITH WARNINGS',GETDATE(),SYSTEM_USER,1);